//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace arvindModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class arvindEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new arvindEntities object using the connection string found in the 'arvindEntities' section of the application configuration file.
        /// </summary>
        public arvindEntities() : base("name=arvindEntities", "arvindEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new arvindEntities object.
        /// </summary>
        public arvindEntities(string connectionString) : base(connectionString, "arvindEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new arvindEntities object.
        /// </summary>
        public arvindEntities(EntityConnection connection) : base(connection, "arvindEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<gala> galas
        {
            get
            {
                if ((_galas == null))
                {
                    _galas = base.CreateObjectSet<gala>("galas");
                }
                return _galas;
            }
        }
        private ObjectSet<gala> _galas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sp> sps
        {
            get
            {
                if ((_sps == null))
                {
                    _sps = base.CreateObjectSet<sp>("sps");
                }
                return _sps;
            }
        }
        private ObjectSet<sp> _sps;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the galas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTogalas(gala gala)
        {
            base.AddObject("galas", gala);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sps EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosps(sp sp)
        {
            base.AddObject("sps", sp);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="arvindModel", Name="gala")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class gala : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new gala object.
        /// </summary>
        /// <param name="imageid">Initial value of the imageid property.</param>
        /// <param name="firstname">Initial value of the firstname property.</param>
        /// <param name="image">Initial value of the image property.</param>
        /// <param name="mobileno">Initial value of the mobileno property.</param>
        /// <param name="image_type">Initial value of the image_type property.</param>
        /// <param name="image_size">Initial value of the image_size property.</param>
        /// <param name="img_id">Initial value of the img_id property.</param>
        public static gala Creategala(global::System.Guid imageid, global::System.String firstname, global::System.Byte[] image, global::System.Int32 mobileno, global::System.String image_type, global::System.Int64 image_size, global::System.Int32 img_id)
        {
            gala gala = new gala();
            gala.imageid = imageid;
            gala.firstname = firstname;
            gala.image = image;
            gala.mobileno = mobileno;
            gala.image_type = image_type;
            gala.image_size = image_size;
            gala.img_id = img_id;
            return gala;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid imageid
        {
            get
            {
                return _imageid;
            }
            set
            {
                if (_imageid != value)
                {
                    OnimageidChanging(value);
                    ReportPropertyChanging("imageid");
                    _imageid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("imageid");
                    OnimageidChanged();
                }
            }
        }
        private global::System.Guid _imageid;
        partial void OnimageidChanging(global::System.Guid value);
        partial void OnimageidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String firstname
        {
            get
            {
                return _firstname;
            }
            set
            {
                OnfirstnameChanging(value);
                ReportPropertyChanging("firstname");
                _firstname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("firstname");
                OnfirstnameChanged();
            }
        }
        private global::System.String _firstname;
        partial void OnfirstnameChanging(global::System.String value);
        partial void OnfirstnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] image
        {
            get
            {
                return StructuralObject.GetValidValue(_image);
            }
            set
            {
                OnimageChanging(value);
                ReportPropertyChanging("image");
                _image = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("image");
                OnimageChanged();
            }
        }
        private global::System.Byte[] _image;
        partial void OnimageChanging(global::System.Byte[] value);
        partial void OnimageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 mobileno
        {
            get
            {
                return _mobileno;
            }
            set
            {
                OnmobilenoChanging(value);
                ReportPropertyChanging("mobileno");
                _mobileno = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mobileno");
                OnmobilenoChanged();
            }
        }
        private global::System.Int32 _mobileno;
        partial void OnmobilenoChanging(global::System.Int32 value);
        partial void OnmobilenoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String image_type
        {
            get
            {
                return _image_type;
            }
            set
            {
                Onimage_typeChanging(value);
                ReportPropertyChanging("image_type");
                _image_type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("image_type");
                Onimage_typeChanged();
            }
        }
        private global::System.String _image_type;
        partial void Onimage_typeChanging(global::System.String value);
        partial void Onimage_typeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 image_size
        {
            get
            {
                return _image_size;
            }
            set
            {
                Onimage_sizeChanging(value);
                ReportPropertyChanging("image_size");
                _image_size = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("image_size");
                Onimage_sizeChanged();
            }
        }
        private global::System.Int64 _image_size;
        partial void Onimage_sizeChanging(global::System.Int64 value);
        partial void Onimage_sizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 img_id
        {
            get
            {
                return _img_id;
            }
            set
            {
                Onimg_idChanging(value);
                ReportPropertyChanging("img_id");
                _img_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("img_id");
                Onimg_idChanged();
            }
        }
        private global::System.Int32 _img_id;
        partial void Onimg_idChanging(global::System.Int32 value);
        partial void Onimg_idChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="arvindModel", Name="sp")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sp : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sp object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="lastname">Initial value of the lastname property.</param>
        /// <param name="mark">Initial value of the mark property.</param>
        /// <param name="attendanse">Initial value of the attendanse property.</param>
        public static sp Createsp(global::System.Int32 id, global::System.String name, global::System.String lastname, global::System.Int32 mark, global::System.String attendanse)
        {
            sp sp = new sp();
            sp.id = id;
            sp.name = name;
            sp.lastname = lastname;
            sp.mark = mark;
            sp.attendanse = attendanse;
            return sp;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String lastname
        {
            get
            {
                return _lastname;
            }
            set
            {
                OnlastnameChanging(value);
                ReportPropertyChanging("lastname");
                _lastname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("lastname");
                OnlastnameChanged();
            }
        }
        private global::System.String _lastname;
        partial void OnlastnameChanging(global::System.String value);
        partial void OnlastnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 mark
        {
            get
            {
                return _mark;
            }
            set
            {
                OnmarkChanging(value);
                ReportPropertyChanging("mark");
                _mark = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mark");
                OnmarkChanged();
            }
        }
        private global::System.Int32 _mark;
        partial void OnmarkChanging(global::System.Int32 value);
        partial void OnmarkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String attendanse
        {
            get
            {
                return _attendanse;
            }
            set
            {
                OnattendanseChanging(value);
                ReportPropertyChanging("attendanse");
                _attendanse = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("attendanse");
                OnattendanseChanged();
            }
        }
        private global::System.String _attendanse;
        partial void OnattendanseChanging(global::System.String value);
        partial void OnattendanseChanged();

        #endregion

    
    }

    #endregion

    
}
