<%@ Page Title="" Language="C#" MasterPageFile="~/Index.master" AutoEventWireup="true" CodeFile="offlinedonations.aspx.cs" Inherits="offlinedonations" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <h1 style="font-weight: normal; padding: 0px; font-size: 30px; line-height: 1em; color: rgb(0, 0, 0); margin: 0px 0px 0.75em; text-transform: uppercase; font-family: 'Fjalla One', arial, sans-serif; font-style: normal; font-variant: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 237, 233);">
        <strong style="font-weight: 700;">OFFLINE DONATIONS</strong></h1>
    <h3 style="font-weight: normal; padding: 0px; font-size: 21px; line-height: 1.2em; color: rgb(0, 0, 0); margin: 0px 0px 1.2em; text-transform: uppercase; font-family: 'Fjalla One', arial, sans-serif; font-style: normal; font-variant: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 237, 233);">
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
        TYPES OF OFFLINE DONATIONS</h3>
    <h2 style="font-weight: normal; padding: 0px; font-size: 24px; line-height: 1.2em; color: rgb(0, 0, 0); margin: 0px 0px 1em; text-transform: uppercase; font-family: 'Fjalla One', arial, sans-serif; font-style: normal; font-variant: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 237, 233);">
        DONATIONS PICK UP</h2>
    <p style="font-weight: normal; padding: 0px; font-size: 24px; line-height: 1.2em; color: rgb(0, 0, 0); margin: 0px 0px 1em; text-transform: uppercase; font-family: 'Fjalla One', arial, sans-serif; font-style: normal; font-variant: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 237, 233);">
        <span style="color: rgb(92, 92, 92); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 237, 233); display: inline !important; float: none;">
        Schedule a donation pick up anywhere in Bangalore.Donate clothes,shoes,toys</span><br 
            style="color: rgb(92, 92, 92); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 237, 233);" />
        <span style="color: rgb(92, 92, 92); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 237, 233); display: inline !important; float: none;">
        and household goods to Vidyranya Foundation.</span><br 
            style="color: rgb(92, 92, 92); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 237, 233);" />
        <strong style="color: rgb(80, 80, 80); font-family: Arial, Helvetica, sans-serif; font-size: 11px; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: 19.796875px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        Telephone:</strong><span 
            style="color: rgb(80, 80, 80); font-family: Arial, Helvetica, sans-serif; font-size: 11px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 19.796875px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); display: inline !important; float: none;"><span 
            class="Apple-converted-space">&nbsp;</span>+91-1204856650&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <strong style="color: rgb(80, 80, 80); font-family: Arial, Helvetica, sans-serif; font-size: 11px; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: 19.796875px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        FAX:</strong><span class="Apple-converted-space">&nbsp;</span>+91-1204856654&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <strong style="color: rgb(80, 80, 80); font-family: Arial, Helvetica, sans-serif; font-size: 11px; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: 19.796875px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        Others:</strong><span class="Apple-converted-space">&nbsp;</span>+91-1204856678</span></p>
    <h3 style="font-weight: normal; padding: 0px; font-size: 21px; line-height: 1.2em; color: rgb(0, 0, 0); margin: 0px 0px 1.2em; text-transform: uppercase; font-family: 'Fjalla One', arial, sans-serif; font-style: normal; font-variant: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 237, 233);">
        CHEQUE/ DD</h3>
    <p style="padding: 0px; margin: 0px 0px 1.5em; color: rgb(92, 92, 92); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 237, 233);">
        We will collect it at your door step please</p>
    <p style="font-weight: normal; padding: 0px; font-size: 24px; line-height: 1.2em; color: rgb(0, 0, 0); margin: 0px 0px 1em; text-transform: uppercase; font-family: 'Fjalla One', arial, sans-serif; font-style: normal; font-variant: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 237, 233);">
        <span style="color: rgb(92, 92, 92); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 237, 233); display: inline !important; float: none;">
        E-Mail&nbsp; <a href="mailto:rohittiwari8724@gmail.com" 
            style="color: rgb(50, 155, 212); text-decoration: underline; font-family: Arial, Helvetica, sans-serif; font-size: 11px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 19.796875px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        mail@snrinfocom.com</a></span></p>
    <p style="font-weight: normal; padding: 0px; font-size: 24px; line-height: 1.2em; color: rgb(0, 0, 0); margin: 0px 0px 1em; text-transform: uppercase; font-family: 'Fjalla One', arial, sans-serif; font-style: normal; font-variant: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 237, 233);">
        <asp:HyperLink ID="HyperLink1" runat="server" Height="10px" 
            NavigateUrl="~/contacts.aspx">vidyaranya center noida</asp:HyperLink>
    </p>
    <h3 style="font-weight: normal; padding: 0px; font-size: 21px; line-height: 1.2em; color: rgb(0, 0, 0); margin: 0px 0px 1.2em; text-transform: uppercase; font-family: 'Fjalla One', arial, sans-serif; font-style: normal; font-variant: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 237, 233);">
        ELECTRONIC CLEARANCE SERVICE (ECS)</h3>
    <p style="padding: 0px; margin: 0px 0px 1.5em; color: rgb(92, 92, 92); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 237, 233);">
        Fill a simple form and send it to us along with a cancelled cheque<br />
        and we will execute your mandate for the given period of time.</p>
    <h3 style="font-weight: normal; padding: 0px; font-size: 21px; line-height: 1.2em; color: rgb(0, 0, 0); margin: 0px 0px 1.2em; text-transform: uppercase; font-family: 'Fjalla One', arial, sans-serif; font-style: normal; font-variant: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 237, 233);">
        SMALL GIFTS</h3>
    <p style="padding: 0px; margin: 0px 0px 1.5em; color: rgb(92, 92, 92); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 237, 233);">
        Posters at centres, painting of the class rooms, study materials, uniforms etc</p>
    <h3 style="font-weight: normal; padding: 0px; font-size: 21px; line-height: 1.2em; color: rgb(0, 0, 0); margin: 0px 0px 1.2em; text-transform: uppercase; font-family: 'Fjalla One', arial, sans-serif; font-style: normal; font-variant: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 237, 233);">
        LARGE GIFTS</h3>
    <p style="padding: 0px; margin: 0px 0px 1.5em; color: rgb(92, 92, 92); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 237, 233);">
        Vehicle for kids and old age people, sponsor one centre for whole year,<br />
        construction of additional rooms,help in getting water (borewells)</p>
    <h2 style="font-weight: normal; padding: 0px; font-size: 24px; line-height: 1.2em; color: rgb(0, 0, 0); margin: 0px 0px 1em; text-transform: uppercase; font-family: 'Fjalla One', arial, sans-serif; font-style: normal; font-variant: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 237, 233);">
        <strong style="font-weight: 700;">BANK TRANSFER:</strong></h2>
    <p style="padding: 0px; margin: 0px 0px 1.5em; color: rgb(92, 92, 92); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 237, 233);">
        Organisation Name&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : Vidyaranya<br />
        Bank Account Number :<b style="font-weight: 700;"><span 
            class="Apple-converted-space">&nbsp;</span>64014146915</b><br />
        Name of the Bank&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: State Bank of Mysore<br />
        Address of the Bank&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : Lady Curzon Road 
        Branch,Bangalore-560001<br />
        Ph.No of the&nbsp; Bank&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : 
        080-25591191<br />
        Type of Bank&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
        : Saving Bank<br />
        IFSC Code No&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
        : SBMY0040016</p>
    <p style="padding: 0px; margin: 0px 0px 1.5em; color: rgb(92, 92, 92); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 237, 233);">
        &nbsp;</p>
    <p style="font-weight: normal; padding: 0px; font-size: 24px; line-height: 1.2em; color: rgb(0, 0, 0); margin: 0px 0px 1em; text-transform: uppercase; font-family: 'Fjalla One', arial, sans-serif; font-style: normal; font-variant: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 237, 233);">
        &nbsp;</p>
    <p style="font-weight: normal; padding: 0px; font-size: 24px; line-height: 1.2em; color: rgb(0, 0, 0); margin: 0px 0px 1em; text-transform: uppercase; font-family: 'Fjalla One', arial, sans-serif; font-style: normal; font-variant: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 237, 233);">
        &nbsp;</p>
    <p style="font-weight: normal; padding: 0px; font-size: 24px; line-height: 1.2em; color: rgb(0, 0, 0); margin: 0px 0px 1em; text-transform: uppercase; font-family: 'Fjalla One', arial, sans-serif; font-style: normal; font-variant: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 237, 233);">
&nbsp;
        <br style="color: rgb(80, 80, 80); font-family: Arial, Helvetica, sans-serif; font-size: 11px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 19.796875px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" />
        <br style="color: rgb(80, 80, 80); font-family: Arial, Helvetica, sans-serif; font-size: 11px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 19.796875px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" />
        <strong style="color: rgb(80, 80, 80); font-family: Arial, Helvetica, sans-serif; font-size: 11px; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: 19.796875px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">&nbsp;</strong></p>
    <p style="font-weight: normal; padding: 0px; font-size: 30px; line-height: 1em; color: rgb(0, 0, 0); margin: 0px 0px 0.75em; text-transform: uppercase; font-family: 'Fjalla One', arial, sans-serif; font-style: normal; font-variant: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 237, 233);">
        &nbsp;</p>
    <br />
</asp:Content>

