//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace arvindModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class arvindEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new arvindEntities object using the connection string found in the 'arvindEntities' section of the application configuration file.
        /// </summary>
        public arvindEntities() : base("name=arvindEntities", "arvindEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new arvindEntities object.
        /// </summary>
        public arvindEntities(string connectionString) : base(connectionString, "arvindEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new arvindEntities object.
        /// </summary>
        public arvindEntities(EntityConnection connection) : base(connection, "arvindEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sp> sps
        {
            get
            {
                if ((_sps == null))
                {
                    _sps = base.CreateObjectSet<sp>("sps");
                }
                return _sps;
            }
        }
        private ObjectSet<sp> _sps;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<result> results
        {
            get
            {
                if ((_results == null))
                {
                    _results = base.CreateObjectSet<result>("results");
                }
                return _results;
            }
        }
        private ObjectSet<result> _results;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sps EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosps(sp sp)
        {
            base.AddObject("sps", sp);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the results EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToresults(result result)
        {
            base.AddObject("results", result);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="arvindModel", Name="result")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class result : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new result object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="results">Initial value of the results property.</param>
        /// <param name="mark">Initial value of the Mark property.</param>
        /// <param name="attendance">Initial value of the Attendance property.</param>
        public static result Createresult(global::System.Int32 id, global::System.String results, global::System.String mark, global::System.String attendance)
        {
            result result = new result();
            result.id = id;
            result.results = results;
            result.Mark = mark;
            result.Attendance = attendance;
            return result;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String results
        {
            get
            {
                return _results;
            }
            set
            {
                OnresultsChanging(value);
                ReportPropertyChanging("results");
                _results = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("results");
                OnresultsChanged();
            }
        }
        private global::System.String _results;
        partial void OnresultsChanging(global::System.String value);
        partial void OnresultsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Mark
        {
            get
            {
                return _Mark;
            }
            set
            {
                OnMarkChanging(value);
                ReportPropertyChanging("Mark");
                _Mark = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Mark");
                OnMarkChanged();
            }
        }
        private global::System.String _Mark;
        partial void OnMarkChanging(global::System.String value);
        partial void OnMarkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Attendance
        {
            get
            {
                return _Attendance;
            }
            set
            {
                OnAttendanceChanging(value);
                ReportPropertyChanging("Attendance");
                _Attendance = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Attendance");
                OnAttendanceChanged();
            }
        }
        private global::System.String _Attendance;
        partial void OnAttendanceChanging(global::System.String value);
        partial void OnAttendanceChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="arvindModel", Name="sp")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sp : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sp object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="lastname">Initial value of the lastname property.</param>
        /// <param name="mark">Initial value of the mark property.</param>
        /// <param name="attendanse">Initial value of the attendanse property.</param>
        public static sp Createsp(global::System.Int32 id, global::System.String name, global::System.String lastname, global::System.Int32 mark, global::System.String attendanse)
        {
            sp sp = new sp();
            sp.id = id;
            sp.name = name;
            sp.lastname = lastname;
            sp.mark = mark;
            sp.attendanse = attendanse;
            return sp;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String lastname
        {
            get
            {
                return _lastname;
            }
            set
            {
                OnlastnameChanging(value);
                ReportPropertyChanging("lastname");
                _lastname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("lastname");
                OnlastnameChanged();
            }
        }
        private global::System.String _lastname;
        partial void OnlastnameChanging(global::System.String value);
        partial void OnlastnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 mark
        {
            get
            {
                return _mark;
            }
            set
            {
                OnmarkChanging(value);
                ReportPropertyChanging("mark");
                _mark = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mark");
                OnmarkChanged();
            }
        }
        private global::System.Int32 _mark;
        partial void OnmarkChanging(global::System.Int32 value);
        partial void OnmarkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String attendanse
        {
            get
            {
                return _attendanse;
            }
            set
            {
                OnattendanseChanging(value);
                ReportPropertyChanging("attendanse");
                _attendanse = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("attendanse");
                OnattendanseChanged();
            }
        }
        private global::System.String _attendanse;
        partial void OnattendanseChanging(global::System.String value);
        partial void OnattendanseChanged();

        #endregion

    
    }

    #endregion

    
}
